---
# This playbook contains common plays that will be run on all nodes.

- name: jenkins-swarm | Create jenkins user
  user: name={{ jenkins_user }} comment="Jenkins user" home={{ jenkins_home_dir }} shell={{ jenkins_shell }}
  ignore_errors: True
  
- name: jenkins-swarm | Create base directory
  file:
    dest="{{ jenkins_home_dir }}"
    state=directory
    owner="{{ jenkins_user }}"
    group="{{ jenkins_group }}"
  tags: jenkins_swarm_setup

- name: jenkins-swarm | Download Jenkins Swarm Client
  get_url: dest={{ jenkins_home_dir }}/swarm-client-{{ jenkins_swarm_client_version }}-jar-with-dependencies.jar url=http://maven.jenkins-ci.org/content/repositories/releases/org/jenkins-ci/plugins/swarm-client/{{ jenkins_swarm_client_version }}/swarm-client-{{ jenkins_swarm_client_version }}-jar-with-dependencies.jar owner={{ jenkins_user }} group={{ jenkins_group }}
  tags: jenkins_swarm_setup
  
- name: jenkins-swarm | Install swarm client script
  template: src=jenkins-swarm-client.sh.j2 dest=/etc/init.d/jenkins-swarm-client mode=0700
  tags: jenkins_swarm_setup
  
- fail: msg=" jenkins-swarm | Missing parameters!"
  when: jenkins_username == '' or jenkins_password == ''

- name: jenkins-swarm | Start the Jenkins swarm client service
  service: name=jenkins-swarm-client state=started enabled=true
  tags: service  
 
